export enum Action {
    ADMIN_EDITED = "AdminEdited",
    AUTO_SENT_PAYMENT_RECALL = "AutoSentPaymentRecall",
    EXHIBITOR_SUBMITTED_CHANGES = "ExhibitorSubmittedChanges",
    ADMIN_SET_PUBLISHED = "AdminSetPublished",
    INITIAL_FORM_SUBMISSION = "InitialFormSubmission",
    ADMIN_VALIDATED = "AdminValidated",
    ADMIN_SET_FAVORITE = "AdminSetFavorite",
    ADMIN_ARCHIVED = "AdminArchived",
    ADMIN_NOTIFIED = "AdminNotified",
    ADMIN_AUTHORIZED_ACCESS = "AdminAuthorizedAccess",
    ADMIN_REFUSED = "AdminRefused",
    ADMIN_DELETED = "AdminDeleted",
    ADMIN_CANCELLED = "AdminCancelled",
}
